language: rust
services: docker
sudo: required

addons:
  apt:
    packages:
      - nettle
      - nettle-dev

matrix:
  include:
    # Linux
    - env: TARGET=x86_64-unknown-linux-gnu
      os: linux
      dist: bionic
      rust: 1.35.0
    - env: TARGET=x86_64-unknown-linux-gnu
      os: linux
      dist: bionic
      rust: stable

    # Linux -- static binary
    - env: TARGET=x86_64-unknown-linux-musl
      os: linux
      dist: bionic
      rust: stable
      addons:
        apt:
          packages:
            - musl
            - musl-dev
            - musl-tools

    # macOS
    - env: TARGET=x86_64-apple-darwin
      os: osx
      rust: stable

    # Testing for future releases of Rust
    - env: TARGET=x86_64-unknown-linux-gnu
      os: linux
      dist: bionic
      rust: beta
    - env: TARGET=x86_64-unknown-linux-gnu
      os: linux
      dist: bionic
      rust: nightly

  allow_failures:
    - env: TARGET=x86_64-unknown-linux-musl
    - rust: beta
    - rust: nightly

before_install:
  #if [[ $TARGET == "x86_64-unknown-linux-musl" ]]; then sudo apt-get install musl musl-dev musl-tools; fi

before_script:
  make _install

script:
  make

